### ISSUE TITLE
codingquark.com isn't resolving

### ISSUE THREAD

**Issue by cjbayliss** [codingquark/codingquark.github.io#4]
G'day! 🙂

I wanted to link a friend to your post on UTF8 in elisp, and noticed that https://codingquark.com isn't resolving. This is the output from dig from my end, pretty sure my ISP wouldn't be blocking anything:

```
cjb@aster:~> cat /etc/resolv.conf
# Generated by dhcpcd from wlan0.dhcp
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 8.8.8.8
nameserver 192.168.43.1
# /etc/resolv.conf.tail can replace this line
cjb@aster:~> dig codingquark.com

; <<>> DiG 9.16.6 <<>> codingquark.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48219
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;codingquark.com.               IN      A

;; ANSWER SECTION:
codingquark.com.        284     IN      A       103.30.226.158

;; Query time: 20 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sun Sep 20 17:30:08 AEST 2020
;; MSG SIZE  rcvd: 60

cjb@aster:~>
```

http://103.30.226.158/ doesn't exists :/ Thankfully http://codingquark.github.io/ still works, so I was able to show them the awesomeness of UTF8 in elisp 🤗

**Comment by codingquark** [comment]
Until I get a backup power supply for my server which is RPi3 FWIW, this issue is going to persist unfortunately. I am sorry for the trouble!

**Comment by cjbayliss** [comment]
No need to apologise. I'd been reading an old post on someone's website being hijacked, then a short time later went to your site to get a link to said post and feared a similar fate. I'm glad its much simpler and not nefarious. 🙂
